apiVersion: 1
datasources:
- name: postgres
  access: proxy
  editable: true
  orgId: 1
  type: postgres
  url: ${POSTGRES_HOST}
  user: ${POSTGRES_USER}
  secureJsonData:
    password: ${POSTGRES_PASS}
  jsonData:
    database: ${POSTGRES_DB}
    sslmode: disable
    postgresVersion: 906
